### PR TITLE
WIP travis: setup for inspirehep/beard-docker travis

### PR DESCRIPTION
**Pull request by jacenkow**
* Update necessary files to use inspirehep/beard-docker travis.

Signed-off-by: Grzegorz Jacenków <grzegorz.jacenkow@cern.ch>

### CODE REVIEW

**Comment by jacenkow** [comment]
@kaplun last chance! At least it is not working for me now :smiley:

**Comment by jacenkow** [comment]
Does not work, at leat I can do DDOS with different .travis.yml files.

**Comment by kaplun** [comment]
So I am not going to merge it right?

**Comment by jacenkow** [comment]
Nah, as soon I will make this thing to pass the test, I let you know.

**Comment by jalavik** [comment]
@jacenkow This is the password and user for the dockerhub space for inspirehep so better we add this. @kaplun

**Comment by kaplun** [comment]
Hei, I think this repo is no longer needed right?

**Comment by jacenkow** [comment]
@kaplun, yeah good to remove :+1:

**Pull request closed without merging**
